Repository magnetis/astro-tokens, pull requests merged in 2021-04, with the labels that each got.

#1 [AST-30] improve initial configuration
  .dependabot/config.yml
  .eslintrc.yml
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.yml
  .travis.yml
  README.md
  package.json
  src/colors/index.ts
  src/fonts/index.ts
  src/gradients/index.ts
  src/index.ts
  src/sizes/index.ts
  src/spaces/index.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#10 [AST-69] Add spaces token
  src/index.ts
  src/spaces/index.ts
Labels: enhancement

#12 [AST-26] Add fonts token
  src/fonts/index.ts
  src/index.ts
Labels: enhancement

#11 [AST-28] Add sizes token
  src/index.ts
  src/sizes/index.ts
Labels: enhancement

#13 [AST-25] [AST-27] Add colors and gradients token
  src/colors/index.ts
  src/gradients/index.ts
  src/index.ts
Labels: enhancement

#15 ci(.travis.yml): update travis config
  .travis.yml
Labels: documentation, enhancement

#16 fix(lint-staged): remove jest from lint-staged
  lint-staged.config.js
Labels: dependencies

#17 chore(package.json): add test script
  .eslintrc.yml
  package.json
Labels: dependencies

#18 ci(.travis.config): add email
  .travis.yml
Labels: dependencies
